name: Publish .NET Package

on:
  push:
    branches:
      - main   # change if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Configure NuGet source
        run: dotnet nuget add source \
              --username ${{ github.actor }} \
              --password ${{ secrets.GITHUB_TOKEN }} \
              --store-password-in-clear-text \
              --name github \
              "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Pack NuGet package (auto-incremented version)
        run: dotnet pack src/Testlemon.Core/Testlemon.Core.csproj \
              --configuration Release \
              -o ./artifacts \
              /p:Version=1.0.${{ github.run_number }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./artifacts/*.nupkg \
              --api-key ${{ secrets.GITHUB_TOKEN }} \
              --source "github"